#!/usr/bin/env bash
# Publishes the dashboard on the public internet via Tailscale Funnel.
#
#   ./serve_demo.sh          # publish publicly over Tailscale Funnel
#   ./serve_demo.sh --local  # serve on 127.0.0.1:8011 only — no Tailscale needed
#   ./serve_demo.sh --stop   # stop serving and take the public URLs down
#   ./serve_demo.sh --status # show what is currently served
#
# --local is the path for anyone reproducing this on their own machine. The
# Tailscale requirement below is only for publishing to the internet from the
# machine that hosts the demo.
#
# Two legs, because an HTTPS page cannot open a ws:// socket:
#
#   https://<host>.ts.net/        -> localhost:8000   the dashboard
#   wss://<host>.ts.net:8443/mqtt -> localhost:9001   the broker's websocket
#
# Funnel terminates TLS with the tailnet's own *.ts.net certificate and
# proxies plaintext to localhost, which is why mosquitto's websocket
# listener is plain ws (mosquitto/mosquitto.conf) — TLS is terminated once,
# at the edge, not twice.
#
# 443 and 8443 are two of the three ports Funnel permits (the third is
# 10000); they are not arbitrary choices.

set -euo pipefail
cd "$(dirname "$0")"

# 8000 is deliberately NOT the default: it is a popular port, and on this
# machine it was already taken by an unrelated container. Funnel proxies
# whatever answers on the port it is pointed at, so a static server that
# failed to bind means Funnel publishes SOMEONE ELSE'S service to the public
# internet. That happened once; hence the port check and the content check
# below, and hence a less contended default.
DASH_PORT="${DCDT_DASH_PORT:-8010}"
WS_PORT="${DCDT_WS_PORT:-9001}"
PIDFILE=".dashboard_http.pid"
# Marker proving the thing answering on DASH_PORT is our dashboard.
MARKER="CRAC-01 Digital Twin"

need_tailscale() {
  command -v tailscale >/dev/null || {
    echo "tailscale is not installed on this machine." >&2; exit 1; }
}

write_config_js() {
  # The viewer credential is read-only by ACL, which is what makes it safe to
  # put in a page anyone can view-source. It is still a password, so it is
  # generated here rather than committed. No hostname goes into the file:
  # app.js derives host and port from location.hostname, so the same file works
  # on localhost and on the public URL.
  if [[ ! -f mosquitto/credentials.json ]]; then
    echo "[serve] no credentials yet — run ./run.sh first" >&2
    exit 1
  fi
  python3 - <<'PY'
import json
viewer = json.load(open("mosquitto/credentials.json"))["viewer"]
with open("dashboard/config.js", "w") as fh:
    fh.write(
        "// Generated by serve_demo.sh -- do not edit, do not commit.\n"
        "// The `viewer` identity can read four topic families and write\n"
        "// nothing at all; see mosquitto/acl.\n"
        "window.DCDT_CONFIG = {\n"
        '  username: "viewer",\n'
        f'  password: "{viewer}",\n'
        "  // host/port left unset: app.js derives them from location.hostname\n"
        "  // so this file is identical on localhost and on the public URL.\n"
        "};\n"
    )
PY
}

case "${1:-}" in
  --local)
    # Everything a reproducer needs and nothing they do not: no Tailscale, no
    # public exposure. Serves the dashboard on loopback against the broker
    # this machine is already running.
    LOCAL_PORT="${DCDT_DASH_PORT:-8011}"
    write_config_js
    echo "[serve] dashboard/config.js written"
    if ss -ltn 2>/dev/null | grep -q ":${LOCAL_PORT} "; then
      echo "[serve] ERROR: port ${LOCAL_PORT} is already in use." >&2
      echo "        Pick another:  DCDT_DASH_PORT=8012 ./serve_demo.sh --local" >&2
      exit 1
    fi
    echo "[serve] dashboard on http://127.0.0.1:${LOCAL_PORT}/  (Ctrl+C to stop)"
    exec python3 -m http.server "$LOCAL_PORT" --bind 127.0.0.1 --directory dashboard
    ;;
  --stop)
    need_tailscale
    tailscale funnel --https=443 off 2>/dev/null || true
    tailscale funnel --https=8443 off 2>/dev/null || true
    [[ -f "$PIDFILE" ]] && kill "$(cat "$PIDFILE")" 2>/dev/null || true
    rm -f "$PIDFILE"
    echo "[serve] funnel off, static server stopped"
    exit 0 ;;
  --status)
    need_tailscale
    tailscale funnel status || true
    exit 0 ;;
esac

need_tailscale

# ------------------------------------------------------ 1. dashboard config
write_config_js

HOSTNAME_TS="$(tailscale status --json | python3 -c \
  'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')"
echo "[serve] dashboard/config.js written for $HOSTNAME_TS"

# ------------------------------------------------------- 2. static server
if [[ -f "$PIDFILE" ]] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
  echo "[serve] static server already running on :$DASH_PORT"
else
  # Refuse to continue if anything else already holds the port. Starting
  # anyway would leave that other service — not ours — on the public URL.
  if ss -ltn 2>/dev/null | grep -q ":${DASH_PORT} "; then
    echo "[serve] ERROR: port ${DASH_PORT} is already in use by another process." >&2
    echo "        Funnel would publish THAT service publicly, not this dashboard." >&2
    echo "        Pick a free port:  DCDT_DASH_PORT=8011 ./serve_demo.sh" >&2
    exit 1
  fi
  python3 -m http.server "$DASH_PORT" --bind 127.0.0.1 --directory dashboard \
    > logs/dashboard_http.log 2>&1 &
  echo $! > "$PIDFILE"
  sleep 1
  if ! kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
    echo "[serve] ERROR: static server exited immediately:" >&2
    tail -3 logs/dashboard_http.log >&2
    rm -f "$PIDFILE"
    exit 1
  fi
  echo "[serve] static server on 127.0.0.1:$DASH_PORT"
fi

# Confirm the port serves OUR page before exposing it. A bound port is not
# proof of the right service — this checks the content, not the socket.
if ! curl -sS --max-time 5 "http://127.0.0.1:${DASH_PORT}/" | grep -q "$MARKER"; then
  echo "[serve] ERROR: http://127.0.0.1:${DASH_PORT}/ is not serving this dashboard." >&2
  echo "        Refusing to expose it. Nothing has been published." >&2
  exit 1
fi
echo "[serve] verified: :${DASH_PORT} is serving this dashboard"

# ------------------------------------------------------------- 3. funnel
echo "[serve] enabling Funnel (this needs HTTPS certificates and the funnel"
echo "        attribute enabled for the tailnet — if the next command prints"
echo "        an admin-console URL, open it, enable, and re-run this script)"

tailscale funnel --bg --https=443  "http://localhost:${DASH_PORT}"
tailscale funnel --bg --https=8443 "http://localhost:${WS_PORT}"

cat <<EOF

[serve] live:

    dashboard  https://${HOSTNAME_TS}/
    broker ws  wss://${HOSTNAME_TS}:8443/mqtt

    Check it from a DIFFERENT network (phone on cellular, not wifi) —
    reaching it from this machine proves nothing about public access.

    ./serve_demo.sh --stop     take it down
    ./serve_demo.sh --status   what is currently served
EOF
